{
    'name': 'Vendor Location',
    'version': '12.0.0.0.0',
    'category': 'Extra Tools',
    'summary': '',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': '',
    'maintainer': '',
    'website': '',
    'live_test_url': '',
    'depends': ['purchase'],
    'demo': [],
    'data': [
        'views/partner.xml',
    ],
    'images': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
